blank_issues_enabled: false
contact_links:
  - name: Question or General Discussion
    url: https://github.com/yourusername/git-toolkit/discussions
    about: Ask questions or start discussions about git-toolkit usage